---
### Specify as necessary ###
description: Executor Autobuilder
substitutions:
  _COMPONENT: "executor"
  _DOCKERFILE: "./executor.Dockerfile"
###########################
github:
  owner: kubeflow
  name: kfserving
  push:
    tag: v0.*.*
### Specify as necessary ###
includedFiles:
- pkg/**
- cmd/**
- vendor/**
###########################
build:
  steps:
  - name: docker
    args:
    - "build"
    - "-t"
    - "gcr.io/$REPO_NAME/${_COMPONENT}:$TAG_NAME"
    - "${_DOCKERFILE}"
  images:
  - gcr.io/$REPO_NAME/${_COMPONENT}:$TAG_NAME
