---
### Specify as necessary ###
description: Pytorch Server Autobuilder
substitutions:
  _COMPONENT: "pytorchserver"
  _DOCKERFILE: "./python/pytorch.Dockerfile"
###########################
github:
  owner: kubeflow
  name: kfserving
  push:
    tag: v0.*.*
### Specify as necessary ###
includedFiles:
- python/**
###########################
build:
  steps:
  - name: docker
    args:
    - "build"
    - "-t"
    - "gcr.io/$REPO_NAME/${_COMPONENT}:$TAG_NAME"
    - "${_DOCKERFILE}"
  images:
  - gcr.io/$REPO_NAME/${_COMPONENT}:$TAG_NAME
